const D=window.GUIDE_DATA,W=document.querySelector('#workspace'),home=W.innerHTML;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(u,t)=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`;
const U={dps:'https://www.dps.texas.gov/section/driver-license/identification-requirements',scheduler:'https://www.txdpsscheduler.com/',county:'https://www.cclerk.hctx.net/PersonalRecords.aspx',houston:'https://www.houstonhealth.org/services/vital-statistics',nj:'https://www.nj.gov/health/vital/order-vital/forms-public/',residency:'https://www.dps.texas.gov/section/driver-license/texas-residency-requirement-driver-licenses-and-id-cards'};
let flow='',answers={},state='Texas';
const states=['Texas','Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','District of Columbia','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming','American Samoa','Guam','Northern Mariana Islands','Puerto Rico','U.S. Virgin Islands','U.S. citizen born abroad','Other country'];
function progress(n){document.querySelectorAll('.step').forEach((e,i)=>e.classList.toggle('active',i===n));}
function reset(){flow='';answers={};state='Texas';W.innerHTML=home;progress(0);bindHome();}
function bindHome(){W.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>start(b.dataset.flow));}
function start(f){if(!['dps','birth','records'].includes(f))throw Error('Unknown service');flow=f;answers={};({dps,birth,records})[f]();}
function head(title,tag){progress(1);W.innerHTML=`<button class="back" id="back">← Choose a different document</button><br><span class="pill">${tag}</span><h2>${title}</h2><div id="form"></div><section class="result" id="result" aria-live="polite" tabindex="-1" hidden></section>`;document.querySelector('#back').onclick=reset;}
function sel(id,label,opts){return `<label class="field" for="${id}">${label}</label><select id="${id}">${opts.map(x=>`<option value="${esc(Array.isArray(x)?x[0]:x)}">${esc(Array.isArray(x)?x[1]:x)}</option>`).join('')}</select>`;}
function check(id,text){return `<label class="check"><input type="checkbox" data-answer="${id}" ${answers[id]?'checked':''}><span>${text}</span></label>`;}
function group(key,title,items,desc){return `<details><summary>${title}</summary><p class="muted">${desc}</p>${items.map((x,i)=>check(key+i,esc(x))).join('')}</details>`;}
const count=p=>Object.keys(answers).filter(k=>k.startsWith(p)&&answers[k]).length;
function binds(){W.querySelectorAll('[data-answer]').forEach(x=>x.onchange=()=>{answers[x.dataset.answer]=x.checked;hideResult();});}
function hideResult(){const r=document.querySelector('#result');if(r){r.hidden=true;r.innerHTML='';}progress(1);}
function result(html){progress(2);const r=document.querySelector('#result');r.hidden=false;r.innerHTML=html;r.focus();r.scrollIntoView({behavior:'smooth',block:'nearest'});}
function ref(name){return `<details class="reference"><summary>Staff reference: ${esc(name)}</summary>${(D.references[name]||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</details>`;}
function hot(){return `<div class="note warn"><h3>Prepare a HOT ID referral</h3><p>On the referral paper the client receives, write:</p><strong style="font-size:24px">order HOT ID</strong><p>Tell the client to return <strong>next week</strong> to pick it up and continue the process.</p><p>HOT means <strong>Homeless Outreach Team</strong>. Your DPS reference says the client must have previously held a Texas ID or driver license, been in Harris County jail, or been in prison. Confirm eligibility with staff first. If none apply, ask the OPID team for an alternative document plan.</p><p>A HOT ID helps with identification; other missing requirements must still be completed.</p></div>`;}
const dg=[['Texas DL or ID with photo, unexpired or expired no more than 2 years','Valid U.S. passport book or card','U.S. citizenship or naturalization certificate with identifiable photo','Unexpired U.S. military ID (active, reserve, or retired)','Qualifying unexpired DHS / USCIS photo identification'],['Original or certified U.S. state / territory or Canadian birth certificate','Original or certified Consular Report of Birth Abroad','Original or certified court order for name or gender change, with name and date of birth'],['HOT ID (supporting document per OPID guide)','Social Security card — actual card','Texas DL or ID expired more than 2 years — actual card','Temporary receipt for Texas DL or ID','Other U.S. state / territory / DC / Canadian DL or ID, unexpired or expired within 2 years','Government agency ID card','Voter registration card','W-2 or 1099 form','School records or school photo ID','Military records (DD-214, DD-215, NGC-22)','Unexpired U.S. military dependent ID','Veteran Health Identification Card','Selective Service card','Certified marriage certificate or divorce decree','Insurance policy valid continuously for 2 years','Texas vehicle registration or title','Texas boat registration or title','Hospital birth record','Medicare or Medicaid card','Immunization records','Unexpired foreign passport','Valid government-issued consular document','Federal parole or release certificate','TDCJ parole or mandatory release certificate','Texas inmate ID / TDCJ identification','Federal inmate ID','Federally recognized tribal membership card','Texas state professional license','Pilot license','Concealed handgun / License to Carry card']];
function dps(){head('Texas driver license or ID','TDL / TID');document.querySelector('#form').innerHTML=sel('service','What service is needed?',[['new','First time or expired more than 2 years'],['renew','Renew — expired no more than 2 years'],['replace','Replace — still valid, lost or stolen'],['unknown','Not sure of current status']])+sel('kind','Which document?',[['id','Texas identification card'],['dl','Texas driver license']])+'<div id="dps-body"></div>';document.querySelector('#service').onchange=()=>{answers={};renderDps();};document.querySelector('#kind').onchange=()=>{delete answers.driving;renderDps();};renderDps();}
function renderDps(){
 hideResult();
 const service=document.querySelector('#service').value,dl=document.querySelector('#kind').value==='dl',el=document.querySelector('#dps-body');
 if(service==='unknown'){el.innerHTML=`<div class="note">Use the DPS scheduler to check available services. Enter personal information only on the official DPS website.</div><p>${link(U.scheduler,'Open DPS appointment scheduler')}</p>`;return;}
 let h='<h3>Select the identity documents the client has</h3><p class="muted">Use original or issuing-agency-certified documents. Select each physical document only once.</p>';
 if(service==='new'){
  h+='<div class="note"><strong>ONE primary document is enough.</strong><br>No secondary or supporting documents are needed to establish identity when the client has an acceptable primary document.</div>';
  h+=group('dpA','Primary identification',dg[0],'Select any one acceptable primary document.').replace('<details>','<details open>');
  h+='<div id="identity-status" aria-live="polite"></div><div id="alternative-identity"><h3>If the client has no primary document</h3><p>Use TWO secondary documents, OR ONE secondary document plus TWO supporting documents.</p>'+group('dpB','Secondary identification',dg[1],'Select two, or select one together with two supporting documents.')+group('dpC','Supporting identification',dg[2],'Needed only when using one secondary document. HOT ID is supporting identification for DPS.')+'</div>';
 }else{
  h+=group('existing','Identity document for renewal or replacement',['Birth certificate','Social Security card','Voter registration card','HOT ID','Another identity document accepted by DPS'],'Your staff cheat sheet calls for one identity document. Confirm the specific service requirements with DPS.');
  if(service==='renew')h+='<p>Bring the birth certificate in case DPS does not have it on file. For clients over 59 needing a new or renewed ID, select that option on the OPID tracking form.</p>';
 }
 h+='<button class="primary" id="evaluate">Show next step</button>';
 h+=`<details><summary>Separate DPS application requirements</summary><p>The supplied chart establishes identity. Residency, Social Security information, citizenship or lawful presence, and any name discrepancies are separate application matters. They do not change the chart’s rule that one primary document is sufficient for identity.</p>${dl?'<p>For a driver license, also check applicable education, testing, insurance, and vehicle-registration requirements.</p>':''}<p>${link(U.dps,'DPS identity rules')} · ${link(U.residency,'Residency and affidavit rules')}</p></details><details><summary>Client needs a mailing address</summary><p>Your LOTS reference lists a free mailbox for one year with photo ID (HOT ID accepted), at 3401 Fannin Street. Call 713-526-0311 to confirm hours and availability. Review the DPS residency affidavit requirements separately.</p>${ref('Lord of the Streets')}</details>`;
 el.innerHTML=h;
 function updatePrimary(){if(service!=='new')return;const primary=count('dpA')>=1;document.querySelector('#alternative-identity').hidden=primary;document.querySelector('#identity-status').innerHTML=primary?'<div class="note success"><strong>Identity requirement met.</strong> One primary document is selected. No secondary or supporting documents are needed.</div>':'';}
 W.querySelectorAll('[data-answer]').forEach(x=>x.onchange=()=>{answers[x.dataset.answer]=x.checked;hideResult();updatePrimary();});
 updatePrimary();
 document.querySelector('#evaluate').onclick=()=>{
  const primary=count('dpA')>=1;
  const identity=service==='new'?(primary||count('dpB')>=2||(count('dpB')>=1&&count('dpC')>=2)):count('existing')>=1;
  if(!identity){result('<h3>More identification is needed</h3><p>'+(service==='new'?'Provide ONE primary document, TWO secondary documents, or ONE secondary plus TWO supporting documents.':'Provide an accepted identity document for the selected service.')+'</p>'+hot());return;}
  result(`<div class="note success"><h3>Identity requirement met</h3><p>${service==='new'&&primary?'The client has ONE primary document. No secondary or supporting documents are needed.':'The selected identity documents meet this guide’s document combination.'}</p></div><a class="linkbutton" href="${U.scheduler}" target="_blank" rel="noopener noreferrer">Open DPS appointment scheduler ↗</a><p class="muted">Review the separate application requirements before the appointment. DPS makes the final determination.</p>`);
 };
}
function birth(){head('Birth certificate','BIRTH RECORD');document.querySelector('#form').innerHTML=sel('state','Where was the client born?',states)+'<div id="birth-body"></div>';document.querySelector('#state').value=state;document.querySelector('#state').onchange=()=>{state=document.querySelector('#state').value;answers={};renderBirth();};renderBirth();}
function renderBirth(){hideResult();const el=document.querySelector('#birth-body');if(state==='Texas'){el.innerHTML=sel('format','What certificate is needed?',[['short','Short form — routine identification'],['long','Long form — passport, dual citizenship, or specifically requested']])+sel('birthplace','Birth location',[['Houston','City of Houston'],['Harris','Elsewhere in Harris County'],['Other','Another Texas county']])+`<h3>Select the documents available</h3><p class="muted">ID / driver license and Social Security card receipts are not accepted. Group A documents must be valid. Select each physical document only once.</p>`+D.birthGroups.map((items,i)=>group('bc'+i,['Group A · Primary ID','Group B · Secondary ID','Group C · Supporting documents'][i],items,['One primary ID is enough. HOT ID acceptance comes from your local OPID reference.','Two secondary IDs are enough.','Use one Group B document plus two distinct Group C documents.'][i])).join('')+check('entitled','Applicant is eligible to request this record; required relationship or legal-authority evidence is available.')+'<button class="primary" id="evaluate">Show next step</button>';binds();['format','birthplace'].forEach(x=>document.getElementById(x).onchange=hideResult);document.querySelector('#evaluate').onclick=()=>{const ok=count('bc0')>=1||count('bc1')>=2||(count('bc1')>=1&&count('bc2')>=2);if(!ok){result('<h3>More identification is needed</h3><p>Provide one Group A, two Group B, or one Group B plus two Group C documents.</p>'+hot());return;}if(!answers.entitled){result('<div class="note warn"><h3>Confirm eligibility to request the record</h3><p>Identification is covered. Confirm the applicant’s relationship or legal authority before the visit.</p></div>');return;}const long=document.querySelector('#format').value==='long',place=document.querySelector('#birthplace').value;result(`<div class="note success"><h3>Identification checklist complete</h3><p>Prepare the application and confirm the receiving office’s requirements.</p></div>`+(long?(place==='Houston'?houstonLocation():place==='Harris'?`<div class="note">Confirm which local registrar holds the long-form record. Harris County Clerk does not hold every Harris County birth; city boundaries matter.</div>${countyLocation()}`:`<h3>Apply where the client was born</h3><p>Contact that Texas county or Texas DSHS for a long-form certificate. Confirm local ID rules, especially if the client has only a HOT ID.</p>${link('https://www.dshs.texas.gov/vital-statistics/birth-records','Texas birth records')}`):countyLocation())+`<p class="muted">HOT ID is listed as accepted in your local staff reference. Confirm current acceptance before the visit.</p>`);};}
else if(state==='Other country')el.innerHTML='<div class="note warn">Your OPID guide does not cover birth certificates from other countries. Ask staff about the appropriate consulate or other referral.</div>';
else if(state==='U.S. citizen born abroad')el.innerHTML=`<div class="note">For a U.S. citizen born abroad, review the State Department’s Consular Report of Birth Abroad process.</div><p>${link('https://www.usa.gov/birth-certificate','Find born-abroad instructions')}</p>`+ref('Out of state BCs instructions');else renderOut(el);}
function countyLocation(){return `<div class="location"><h3>Harris County Clerk · Texas birth records</h3><strong>201 Caroline Street, Suite 330, Houston, TX 77002</strong><p>Monday–Friday, 8 a.m.–4:30 p.m.<br>Phone: 713-274-8686</p><p>Short-form certificates are available for Texas births, subject to record availability. For a long form, confirm the registrar holding the original.</p>${link(U.county,'County record coverage, fees, and office details')}</div>`;}
function houstonLocation(death=false){return `<div class="location"><h3>City of Houston · Bureau of Vital Statistics</h3><strong>8000 North Stadium Drive, Houston, TX 77054</strong><p>City of Houston ${death?'death':'birth'} records.<br>Walk-ins Monday–Thursday, 8 a.m.–4 p.m.; arrive by 3 p.m. No Friday walk-ins.</p>${link(U.houston,'Houston records and visit details')}</div>`;}
function special(){let k=state;if(k==='New York')k=document.querySelector('#nyc')?.value==='yes'?'New York City':'New York State';if(k==='Illinois')k=/cook/i.test(document.querySelector('#county')?.value||'')?'Illinois-Cook County':'Illinois-state';return D.special[k]||'No additional state-specific instructions are listed in your OPID reference. Check the current issuing-office application.';}
function searchUrl(){const county=document.querySelector('#county')?.value.trim()||'';const loc=state==='New York'&&document.querySelector('#nyc')?.value==='yes'?'New York City':`${state} ${county}`;return 'https://www.google.com/search?q='+encodeURIComponent(loc+' Birth certificate by mail application');}
function updateSpecial(){document.querySelector('#special').textContent=special();const n=document.querySelector('#nyc-notes');if(n)n.hidden=document.querySelector('#nyc').value!=='yes';document.querySelector('#lookup').href=searchUrl();const cover=document.querySelector('[data-answer="outCover"]');if(cover){cover.disabled=!coverRequired();if(cover.disabled){cover.checked=false;answers.outCover=false;}document.querySelector('#cover-note').textContent=coverRequired()?'Use the standard OPID cover letter or the custom letter in the state instructions.':'Do not include a cover letter for '+(state==='Florida'?'Florida':'New York City')+', per the OPID instructions.';}hideResult();}
function renderOut(el){el.innerHTML=(state==='New York'?sel('nyc','Born in New York City?',[['no','No — elsewhere in New York State'],['yes','Yes — Manhattan, Bronx, Queens, Brooklyn, or Staten Island']]):'')+'<label class="field" for="county">County or city of birth</label><input type="text" id="county" autocomplete="off" placeholder="For example, Cook County"><div class="note"><strong>OPID special instructions</strong><p id="special"></p><small>Staff-reference instructions: confirm current ID acceptance and processing times with the issuing office.</small></div>'+(state==='New Jersey'?`<p>${link(U.nj,'Official New Jersey forms')}</p>`:'')+(state==='New York'?`<div id="nyc-notes" hidden>${ref('NYC instructions for birth certificates - update 12.3.25')}</div>`:'')+`<p><a id="lookup" target="_blank" rel="noopener noreferrer">Find the current application ↗</a></p><h3>Documents to include</h3><p class="muted">Select either accepted ID copies or other accepted documents, plus a cover letter when required.</p>`+check('outCopy','Required state-issued ID copies, including both sides in color per OPID.')+check('outOther','Other documents accepted by the state (call if unsure).')+check('outCover','Cover letter')+'<p id="cover-note" class="muted"></p><div class="note"><strong>Information to be aware of</strong><ul><li>Confirm who is eligible to request the record under the issuing office’s rules.</li><li>Use the current application and follow its signature and notarization instructions.</li><li>Confirm the fee, payable-to name, and application mailing address.</li><li>Include a self-addressed stamped envelope if required.</li><li>Check the current processing time and explain the expected return date to the client.</li><li>Follow the special state instructions above, including any custom cover letter.</li></ul></div>'+'<button class="primary" id="evaluate">Show next step</button>'+ref('Out of state BCs instructions');document.querySelector('#county').oninput=()=>{clearOutChecks();updateSpecial();};if(document.querySelector('#nyc'))document.querySelector('#nyc').onchange=()=>{clearOutChecks();updateSpecial();};updateSpecial();binds();document.querySelector('#evaluate').onclick=evaluateOut;}
function clearOutChecks(){answers={};W.querySelectorAll('[data-answer]').forEach(x=>x.checked=false);}
function coverRequired(){return state!=='Florida'&&!(state==='New York'&&document.querySelector('#nyc')?.value==='yes');}
function evaluateOut(){if(!answers.outCopy&&!answers.outOther){result(`<div class="note warn"><h3>Accepted identification is needed</h3><p>Provide the required state-issued ID copies or other documents accepted by the state. Call the issuing office if unsure.</p><p>If the client has neither, ask about an eligible relative or legal guardian who can apply, or another accepted document route. Mark the OPID tracking form Pending.</p><p>Call the issuing office before ordering a HOT ID for an out-of-state certificate. Use the referral below only if the office confirms it will help and the client is eligible.</p></div>${hot()}`);return;}if(coverRequired()&&!answers.outCover){result('<div class="note warn"><h3>Add the cover letter</h3><p>Use the standard OPID cover letter or the custom letter specified in the state instructions.</p></div>');return;}if(!document.querySelector('#county').value.trim()&&!(state==='New York'&&document.querySelector('#nyc')?.value==='yes')){result('<div class="note warn">Enter the county or city of birth above to create the application search.</div>');document.querySelector('#county').focus();return;}result(`<div class="note success"><h3>Prepare the mail application</h3><p>The review checklist is complete. Use the official issuing-office result from this search.</p></div><a class="linkbutton" href="${esc(searchUrl())}" target="_blank" rel="noopener noreferrer">Search for the mail application ↗</a><h3>Use the OPID return contact</h3><p>First Presbyterian Church-ID<br>5300 Main Street<br>Houston TX 77004<br>opidoffice@msmhouston.org · 281-833-3499</p><ol><li>Include the accepted ID copies or other accepted documents. Include the cover letter when required; omit it for Florida and NYC. Include a self-addressed stamped envelope when required.</li><li>Complete the OPID tracking form with fee, payable-to details, and office address. For city/county applications, choose “Other” under MBVD State.</li><li>If the client will need ID/DL after the certificate arrives, create a second tracking form marked Pending.</li><li>Give an approximate return date based on the current agency estimate. Confirm client contact details.</li><li>Date notes and sign with your first name and last initial. Clients returning for a DPS check should come Tuesday or Thursday, 9–11 a.m., per the staff guide.</li></ol>`);}
function records(){head('Marriage, death, or divorce record','VITAL RECORDS');document.querySelector('#form').innerHTML=sel('record','Which record?',['Marriage','Death','Divorce'])+sel('record-place','Where did the event occur?',[['Houston','City of Houston'],['Harris','Elsewhere in Harris County'],['Other','Another county or state']])+'<div id="record-body"></div>';['record','record-place'].forEach(id=>document.querySelector('#'+id).onchange=renderRecord);renderRecord();}
function renderRecord(){hideResult();const type=document.querySelector('#record').value,place=document.querySelector('#record-place').value;let h='';if(place==='Other')h=`<h3>Apply to the county where the event occurred</h3><ol><li>Download the current county application. For divorce, call first for case number and certified-copy cost.</li><li>Confirm applicant eligibility and accepted photo ID; photocopy the accepted ID.</li><li>Use First Presbyterian Church-ID, 5300 Main Street, Houston TX 77004 for the return mailing address.</li><li>Give Finance the fee, payable-to entity, and mailing address. For divorce, put these in the OPID Tracking Form Notes.</li><li>Complete required signatures and notarization. Place the application in the admin office IN box for mailing.</li></ol>`;
else if(type==='Divorce')h=`<h3>Contact Harris County District Clerk</h3><p>Call <strong>832-927-5800</strong> and choose the Family option. Confirm the case number, certified-copy fee, and current pickup instructions.</p><ul><li>Names and dates of birth of both parties</li><li>Date of divorce and case number, if known</li></ul><p>Request the check. Your staff guide lists 201 Caroline Street, Suite 420 for pickup; confirm when calling. The client needs valid photo ID.</p>`;
else if(type==='Death')h=place==='Houston'?`<h3>City of Houston death record</h3><p>Use the Houston registrar for deaths within Houston city limits. Confirm eligibility, photo ID, and the certificate fee before requesting a check.</p>${houstonLocation(true)}`:`<h3>Confirm the registrar before sending the client</h3><p>Harris County Clerk holds deaths outside several city jurisdictions. Check coverage, applicant eligibility, accepted photo ID, and fees. Request a check and prepare the certified birth/death record application.</p><p>201 Caroline Street, Suite 330, Houston. Monday–Friday, 8 a.m.–4:30 p.m.</p>${link(U.county,'Confirm death-record coverage')}`;
else h=`<h3>Harris County marriage record</h3><p>For a marriage license filed with Harris County, request a check for the certified copy and send the client with valid photo ID. Your staff reference lists $25; confirm the current fee and pickup suite before requesting payment.</p><p>Harris County Clerk, 201 Caroline Street, Houston.</p>${link(U.county,'Marriage records and current fees')}`;
if(type==='Divorce')h+='<div class="note warn">If the divorce is not finalized, or another issue prevents release, tell the client OPID cannot apply for the final decree yet.</div>';
if(type!=='Divorce'&&place!=='Other')h+='<div class="note">Your staff reference lists HOT ID as accepted locally. Confirm current acceptance with the receiving office. Applicant eligibility and record jurisdiction must also be satisfied.</div>';
h+='<details><summary>Original staff instructions</summary><p class="muted">The original reference below may contain older fees, suites, or jurisdiction guidance. Use the current agency links above to resolve differences.</p>'+ref('Marriage, Divorce and Death Records')+'</details>';document.querySelector('#record-body').innerHTML=h;progress(2);}
document.querySelector('#reset').onclick=reset;bindHome();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'start_document_guide',description:'Open a staff guide; does not submit an application or order identification.',inputSchema:{type:'object',properties:{service:{type:'string',enum:['dps','birth','records']}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||!['dps','birth','records'].includes(input.service))throw Error('Choose dps, birth, or records');start(input.service);return {service:flow,title:W.querySelector('h2').textContent};}});}catch(e){console.warn('Guide tools unavailable',e);}}
